# postgres
#
defaults_development: &defaults_development
  adapter: postgresql
  encoding: unicode
  username: max1
  password: 123
  host: localhost

development:
  database: e1
  <<: *defaults_development

test:
  database: e2
  <<: *defaults_development
