# postgres
#
defaults_development: &defaults_development
  adapter: postgresql
  encoding: unicode
  username: al
  password: a1234
  host: localhost123

development:
  database: easy1
  <<: *defaults_development

test:
  database: easy2
  <<: *defaults_development
